#!/usr/bin/perl

$sect = 'none';

while(<>) {
    if (/^	(\.(text|data|sdata|sbss|sdata2))/) {
        $sect = $1;
    }
    if (/^	(\.section.*)/) {
        $sect = $1;
    }
    if (/([A-Za-z_][A-Za-z0-9_]*):/) {
        printf ("%32s: %s\n", $1, $sect);
    }
    if (/([A-Za-z_][A-Za-z0-9_]*)\)?\@sda/) {
        printf ("%32s: short reference\n", $1);
    }
}
