#!/bin/sh

for i in $*; do
  mv $i $i.bak
  sed -e '/<span class="keyword">Proof<\/span> *\./,/<span class="keyword">\(Qed\|Defined\)<\/span> *\./d' \
      -e "s/\"'do' X <- A ; B\" error_monad_scope/doXAB error_monad_scope/g" \
      -e "s/\"'do' X <- A ; B\"/doXAB/g" \
      -e "s/\"'do' ( X , Y ) <- A ; B\"/doXYAB/g" \
      $i.bak > $i
  rm $i.bak
done

