#!/bin/sh

echo "Fixing file names..."
mv list.ml CoqList.ml
mv list.mli CoqList.mli
mv string.ml CoqString.ml
mv string.mli CoqString.mli
mv int.ml CoqInt.ml
mv int.mli CoqInt.mli

echo "Conversion List -> CoqList, String -> CoqString, Int -> CoqInt..."
./convert *.mli *.ml

echo "Patching files..."
for i in *.patch; do patch < $i; done
